name: Publish As NuGet Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore 
    - name: Build NuGet Package
      run: dotnet build --configuration Release
    - name: Publish NuGet Package to Github
      run: dotnet nuget push source ${{github.workspace}}/bin/Release/*.nupkg -k ${{secrets.GITHUB_TOKEN}} -s "https://nuget.pkg.github.com/orgs/roman015-com/index.json"
